import io
import pandas as pd

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

from product_ranking import (
    top_products,
    get_inventory_data,
    get_demand_trend,
)




def _empty_msg_df(message: str) -> pd.DataFrame:
    return pd.DataFrame({"Message": [message]})


def build_forecast_report_df(csv_path: str) -> pd.DataFrame:
    rows = top_products(csv_path, n=10)
    if not rows:
        return _empty_msg_df("No data available. Please upload a dataset first.")

    df = pd.DataFrame(rows)
    df = df.rename(columns={
        "product_name": "Product",
        "total_quantity": "Total Quantity (Demand)",
    })
    df.insert(0, "Rank", range(1, len(df) + 1))
    return df


def build_trend_report_df(csv_path: str) -> pd.DataFrame:
    rows = get_demand_trend(csv_path, months=12)
    if not rows:
        return _empty_msg_df("No data available. Please upload a dataset first.")

    df = pd.DataFrame(rows)
    df = df.rename(columns={"month": "Month", "demand": "Total Demand"})
    return df


def build_inventory_report_df(csv_path: str) -> pd.DataFrame:
    rows = get_inventory_data(csv_path)
    if not rows:
        return _empty_msg_df("No data available. Please upload a dataset first.")

    df = pd.DataFrame(rows)
    df = df.rename(columns={
        "product_name": "Product",
        "current_stock": "Current Stock",
        "predicted_demand": "Predicted Demand",
        "recommended_stock": "Recommended Stock",
        "status": "Status",
    })
    return df




def df_to_excel_bytes(df: pd.DataFrame, sheet_name: str = "Report") -> bytes:
    buf = io.BytesIO()
    safe_sheet_name = sheet_name[:31] or "Report"  # Excel sheet name limit
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name=safe_sheet_name)

        # Auto-fit column widths roughly based on content length
        worksheet = writer.sheets[safe_sheet_name]
        for col_idx, col in enumerate(df.columns, start=1):
            max_len = max(
                [len(str(col))] + [len(str(v)) for v in df[col].astype(str).tolist()]
            )
            worksheet.column_dimensions[
                worksheet.cell(row=1, column=col_idx).column_letter
            ].width = min(max_len + 4, 40)

    return buf.getvalue()


def df_to_pdf_bytes(title: str, description: str, df: pd.DataFrame) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=36, bottomMargin=36, leftMargin=36, rightMargin=36,
    )
    styles = getSampleStyleSheet()

    elements = [
        Paragraph(title, styles["Title"]),
        Paragraph(description, styles["Normal"]),
        Spacer(1, 16),
        Paragraph("Generated by ChainSight AI Executive Analytics Center", styles["Italic"]),
        Spacer(1, 12),
    ]

    data = [list(df.columns)] + df.astype(str).values.tolist()
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)

    doc.build(elements)
    return buf.getvalue()


REPORTS = {
    "forecast": {
        "title": "Monthly Forecast Report",
        "description": "Top high-demand products ranked by total quantity from your uploaded dataset.",
        "builder": build_forecast_report_df,
    },
    "trend": {
        "title": "Demand Trend Analysis",
        "description": "Monthly demand totals over the most recent months.",
        "builder": build_trend_report_df,
    },
    "inventory": {
        "title": "Inventory Report",
        "description": "Current inventory status and AI stock recommendations.",
        "builder": build_inventory_report_df,
    },
}